### ISSUE TITLE
Which CUDA Toolkit version to use?

### ISSUE THREAD

**Issue by MarcoMeter** [cbovar/ConvNetSharp#60]
Hey,

I'm getting a DllNotFoundException on GpuContext.cs:26.

Additional information: Unable to load DLL 'cudnn64_6.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

On a fresh Win10 64bit, I'm running VS 2015, VS 2017 and cuda 8. According to the managedCuda Repo, 7.5 should be the matching version, so I installed it in coexistence of version 8, which did not resolve the issue. I did the builds using VS 2015, because the cuda toolkit does not come with a VS 2017 integration yet. Before I start installing and unistalling cuda versions, I'd like to clarify this concern. As the missing dll includes the digit 6, does that mean, that cuda toolkit version 6 is the right version to go with for this repo?

**Comment by cbovar** [comment]
Hi,

Cuda Toolkit version 8 should work.

I now realize there is an important information missing in the README: you need to download Cudnn library version 6.0 for CUDA 8.0 ([here](https://developer.nvidia.com/cudnn)) **and** you must reference it in the PATH environment variable.

**Comment by MarcoMeter** [comment]
Thanks, issue is resolved.

I added the cudnn64_6.dll to the ../Windows/System32/ directory.
